version: "3.7"

services:

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
      - APP_NAME=smarthive
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
